'use client';
import { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase/client';

type Region='MY'|'ID'|'PH';
type Flag={enabled:boolean;message:string|null;updated_at:string};
type Config={region:string;features:Record<string,Flag>;snapshots:{category:string;week_id:string|null;rows:number;generated_at:string}[];weeks:{id:string;number:number}[]};
const FEATURES=[
 {key:'predictions',name:'Match Predictions',copy:'Winner and exact-score submissions'},
 {key:'mvp',name:'Weekly MVP',copy:'Regional weekly MVP voting'},
 {key:'fantasy',name:'Fantasy Team',copy:'Lineups, transfers and fantasy scoring'},
 {key:'leaderboard',name:'Leaderboards',copy:'Regional public ranking tables'},
 {key:'draft_lab',name:'Live Draft Lab',copy:'Public draft companion and model bundle'}
];

export default function AdminRegionalOperations({region,notify}:{region:Region;notify:(message:string)=>void}){
 const [config,setConfig]=useState<Config|null>(null);const [busy,setBusy]=useState(false);const [weekId,setWeekId]=useState('');const [messages,setMessages]=useState<Record<string,string>>({});
 async function load(){if(!supabase)return;const{data,error}=await supabase.rpc('admin_regional_operations_status',{target_region:region});if(error){notify(error.message);return}const next=data as unknown as Config;setConfig(next);setWeekId(current=>current||next.weeks[0]?.id||'');setMessages(Object.fromEntries(Object.entries(next.features||{}).map(([key,value])=>[key,value.message||''])))}
 useEffect(()=>{load()},[region]);
 async function toggle(key:string){if(!supabase||!config)return;const current=config.features[key]?.enabled??true;const next=!current;if(!next&&!window.confirm(`Pause ${FEATURES.find(item=>item.key===key)?.name} for ${region}?`))return;setBusy(true);const{error}=await supabase.rpc('admin_set_regional_feature',{target_region:region,target_feature:key,target_enabled:next,target_message:messages[key]||''});setBusy(false);if(error){notify(error.message);return}notify(`${FEATURES.find(item=>item.key===key)?.name} ${next?'enabled':'paused'} for ${region}.`);await load()}
 async function saveMessage(key:string){if(!supabase||!config)return;setBusy(true);const{error}=await supabase.rpc('admin_set_regional_feature',{target_region:region,target_feature:key,target_enabled:config.features[key]?.enabled??true,target_message:messages[key]||''});setBusy(false);if(error){notify(error.message);return}notify('Public regional message saved.');await load()}
 async function refresh(targetWeek?:string){if(!supabase)return;setBusy(true);const{data,error}=await supabase.rpc('admin_refresh_leaderboard_snapshots',{target_region:region,...(targetWeek?{target_week:targetWeek}:{})});setBusy(false);if(error){notify(error.message);return}const result=data as {rows?:number};notify(`${result.rows||0} leaderboard snapshot rows generated.`);await load()}
 if(!config)return<section className="panel operationsLoading">LOADING REGIONAL OPERATIONS…</section>;
 const allOpen=FEATURES.every(item=>config.features[item.key]?.enabled!==false);
 return<div className="regionalOperations"><section className="operationsHero"><div><span>REGIONAL TRAFFIC CONTROL</span><h2>{region} Operations</h2><p>Pause one regional feature, publish a service message or rebuild leaderboard snapshots without affecting the other competitions.</p></div><aside><small>REGIONAL STATUS</small><strong className={allOpen?'open':'limited'}>{allOpen?'ALL SYSTEMS OPEN':'LIMITED SERVICE'}</strong></aside></section><section className="panel featureControls"><header><div><span>FEATURE SWITCHES</span><h2>Independent regional controls</h2></div><b>{region} ONLY</b></header><div>{FEATURES.map(item=>{const flag=config.features[item.key]||{enabled:true,message:null,updated_at:''};return<article className={flag.enabled?'enabled':'paused'} key={item.key}><button type="button" className="featureToggle" disabled={busy} onClick={()=>toggle(item.key)} aria-label={`${flag.enabled?'Pause':'Enable'} ${item.name}`}><i/><span>{flag.enabled?'OPEN':'PAUSED'}</span></button><div className="featureIdentity"><h3>{item.name}</h3><p>{item.copy}</p></div><div className="featureMessage"><input value={messages[item.key]||''} onChange={e=>setMessages(current=>({...current,[item.key]:e.target.value}))} placeholder="Optional public service message"/><button type="button" disabled={busy} onClick={()=>saveMessage(item.key)}>SAVE MESSAGE</button></div></article>})}</div></section><section className="panel snapshotControl"><header><div><span>PRECOMPUTED RANKINGS</span><h2>Leaderboard snapshots</h2><p>Visitors read these compact regional tables instead of recalculating the complete score ledger.</p></div></header><div className="snapshotActions"><article><span>SEASON OVERALL</span><p>Prediction, fantasy and total rankings for the active season.</p><button className="primary" disabled={busy} onClick={()=>refresh()}>REFRESH OVERALL</button></article><article><span>WEEKLY SNAPSHOT</span><select value={weekId} onChange={e=>setWeekId(e.target.value)}>{config.weeks.map(week=><option value={week.id} key={week.id}>WEEK {week.number}</option>)}</select><button className="secondary" disabled={busy||!weekId} onClick={()=>refresh(weekId)}>REFRESH WEEK</button></article></div><div className="snapshotTable"><div><span>SCOPE</span><span>CATEGORY</span><span>ROWS</span><span>GENERATED</span></div>{config.snapshots.length?config.snapshots.map((snapshot,index)=><div key={`${snapshot.category}-${snapshot.week_id}-${index}`}><b>{snapshot.week_id?`WEEK ${config.weeks.find(week=>week.id===snapshot.week_id)?.number||'—'}`:'SEASON'}</b><span>{snapshot.category.toUpperCase()}</span><strong>{snapshot.rows}</strong><time>{new Date(snapshot.generated_at).toLocaleString()}</time></div>):<p>NO SNAPSHOTS GENERATED YET.</p>}</div></section><footer className="operationsNote"><b>FAILURE ISOLATION</b><span>Changes on this screen apply only to {region}. Malaysia, Indonesia and Philippines remain independently controllable.</span></footer></div>
}
