'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';

type Region = 'MY' | 'ID' | 'PH';
type View = 'dashboard' | 'predictions' | 'fantasy' | 'leagues' | 'leaderboard' | 'admin';
type Session = { name: string; email: string; joined: Region[]; active?: Region; picks: Record<string,string>; exactScores:Record<string,string>; submittedAt:Partial<Record<Region,string>>; captains:Partial<Record<Region,string>>; rosters:Partial<Record<Region,string[]>>; transfers:Partial<Record<Region,number>> };

type Match = { id:string; time:string; home:string; homeCode:string; away:string; awayCode:string };

const REGIONS: Record<Region,{name:string;flag:string;logo:string;timezone:string;accent:string}> = {
  MY:{name:'MPL Malaysia',flag:'🇲🇾',logo:'/leagues/mpl-my.png',timezone:'MYT',accent:'#60baff'},
  ID:{name:'MPL Indonesia',flag:'🇮🇩',logo:'/leagues/mpl-id.png',timezone:'WIB',accent:'#ff536b'},
  PH:{name:'MPL Philippines',flag:'🇵🇭',logo:'/leagues/mpl-ph.png',timezone:'PHT',accent:'#ffc83d'}
};

const MATCHES: Record<Region,Match[]> = {
  MY:[
    {id:'my-1',time:'SAT · 3:00 PM',home:'Selangor Red Giants',homeCode:'SRG',away:'HomeBois',awayCode:'HB'},
    {id:'my-2',time:'SAT · 6:30 PM',home:'ONIC Malaysia',homeCode:'ONIC',away:'Team Flash',awayCode:'TFL'}
  ],
  ID:[
    {id:'id-1',time:'SAT · 4:15 PM',home:'RRQ Hoshi',homeCode:'RRQ',away:'ONIC Esports',awayCode:'ONIC'},
    {id:'id-2',time:'SUN · 2:00 PM',home:'Bigetron Alpha',homeCode:'BTR',away:'Geek Fam',awayCode:'GEEK'}
  ],
  PH:[
    {id:'ph-1',time:'FRI · 7:30 PM',home:'Team Liquid PH',homeCode:'TLPH',away:'Aurora Gaming',awayCode:'RORA'},
    {id:'ph-2',time:'SUN · 5:00 PM',home:'Falcons AP.Bren',homeCode:'FCAP',away:'ONIC Philippines',awayCode:'ONIC'}
  ]
};

const MVP: Record<Region,{name:string;role:string;team:string}[]> = {
  MY:[{name:'Sekys',role:'Jungler',team:'SRG'},{name:'Innocent',role:'Gold',team:'SRG'},{name:'Xorn',role:'Roamer',team:'HB'},{name:'Stormie',role:'Mid',team:'ONIC'}],
  ID:[{name:'Kiboy',role:'Roamer',team:'ONIC'},{name:'Skylar',role:'Gold',team:'RRQ'},{name:'Sanz',role:'Mid',team:'ONIC'},{name:'Kyy',role:'Roamer',team:'BTR'}],
  PH:[{name:'Sanford',role:'EXP',team:'TL PH'},{name:'Kelra',role:'Gold',team:'Aurora'},{name:'Sanji',role:'Mid',team:'TL PH'},{name:'Oheb',role:'Gold',team:'Falcons'}]
};

const ROSTERS: Record<Region,{name:string;role:string;pts:number}[]> = {
  MY:[{name:'Sekys',role:'Jungle',pts:78},{name:'Xorn',role:'Roam',pts:42},{name:'Yums',role:'EXP',pts:51},{name:'Stormie',role:'Mid',pts:56},{name:'Innocent',role:'Gold',pts:59}],
  ID:[{name:'Kairi',role:'Jungle',pts:81},{name:'Kiboy',role:'Roam',pts:48},{name:'Dyrennn',role:'EXP',pts:52},{name:'Sanz',role:'Mid',pts:61},{name:'Skylar',role:'Gold',pts:64}],
  PH:[{name:'KarlTzy',role:'Jungle',pts:80},{name:'Jaypee',role:'Roam',pts:45},{name:'Sanford',role:'EXP',pts:60},{name:'Sanji',role:'Mid',pts:63},{name:'Kelra',role:'Gold',pts:69}]
};

const initialSession: Session = {name:'',email:'',joined:[],picks:{},exactScores:{},submittedAt:{},captains:{},rosters:{},transfers:{}};

export default function App(){
  const [ready,setReady]=useState(false);
  const [session,setSession]=useState<Session>(initialSession);
  const [view,setView]=useState<View>('dashboard');
  const [regionModal,setRegionModal]=useState(false);
  const [toast,setToast]=useState('');

  useEffect(()=>{
    try { const raw=localStorage.getItem('fmpl_session'); if(raw){const saved=JSON.parse(raw);setSession({...initialSession,...saved,picks:saved.picks||{},exactScores:saved.exactScores||{},submittedAt:saved.submittedAt||{},captains:saved.captains||{},rosters:saved.rosters||{},transfers:saved.transfers||{}})} } catch {}
    setReady(true);
  },[]);
  useEffect(()=>{ if(ready && session.email) localStorage.setItem('fmpl_session',JSON.stringify(session)); },[session,ready]);

  const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(''),2600)};
  if(!ready) return <div className="loading"><Logo/><span>Preparing the arena…</span></div>;
  if(!session.email) return <Auth onComplete={(name,email)=>setSession({...initialSession,name,email})}/>;
  if(!session.active) return <RegionGate joined={session.joined} onChoose={(r)=>joinRegion(r)} />;

  function joinRegion(region:Region){
    setSession(s=>({...s,active:region,joined:s.joined.includes(region)?s.joined:[...s.joined,region]}));
    setRegionModal(false);setView('dashboard');notify(`${REGIONS[region].name} selected`);
  }
  function signOut(){ localStorage.removeItem('fmpl_session'); setSession(initialSession); setView('dashboard'); }
  function savePick(key:string,value:string){ setSession(s=>({...s,picks:{...s.picks,[key]:value}})); }
  function saveScore(key:string,value:string){setSession(s=>({...s,exactScores:{...s.exactScores,[key]:value}}))}
  function submitRegion(r:Region){setSession(s=>({...s,submittedAt:{...s.submittedAt,[r]:new Date().toISOString()}}));notify('Week 5 predictions submitted successfully!')}
  function saveCaptain(r:Region,name:string){setSession(s=>({...s,captains:{...s.captains,[r]:name}}));notify(`${name} is your Week 5 captain.`)}
  function makeTransfer(r:Region,outName:string,inName:string){setSession(s=>{const current=s.rosters[r]||ROSTERS[r].map(p=>p.name);const next=current.map(n=>n===outName?inName:n);const left=(s.transfers[r]??3)-1;const captains={...s.captains};if(captains[r]===outName)captains[r]=inName;return {...s,rosters:{...s.rosters,[r]:next},transfers:{...s.transfers,[r]:left},captains}});notify(`${inName} transferred in for ${outName}.`)}
  const region=session.active;

  return <div className={`shell theme${region}`}>
    <Sidebar view={view} setView={setView} region={region}/>
    <main>
      <Topbar session={session} region={region} onRegion={()=>setRegionModal(true)} onAdmin={()=>setView('admin')} onSignOut={signOut}/>
      {view==='dashboard' && <Dashboard session={session} region={region} setView={setView} picks={session.picks} savePick={savePick}/>} 
      {view==='predictions' && <Predictions region={region} picks={session.picks} scores={session.exactScores} submittedAt={session.submittedAt[region]} savePick={savePick} saveScore={saveScore} submit={()=>submitRegion(region)} notify={notify}/>} 
      {view==='fantasy' && <Fantasy region={region} captain={session.captains[region]} rosterNames={session.rosters[region]} transfers={session.transfers[region]??3} saveCaptain={name=>saveCaptain(region,name)} makeTransfer={(outName,inName)=>makeTransfer(region,outName,inName)} notify={notify}/>} 
      {view==='leagues' && <Leagues region={region} notify={notify}/>} 
      {view==='leaderboard' && <Leaderboard region={region} manager={session.name}/>} 
      {view==='admin' && <AdminConsole region={region} notify={notify}/>} 
    </main>
    <MobileNav view={view} setView={setView}/>
    {regionModal && <RegionGate joined={session.joined} onChoose={joinRegion} close={()=>setRegionModal(false)}/>} 
    <div className={`toast ${toast?'show':''}`}>{toast}</div>
  </div>;
}

function Logo(){return <div className="logo"><img className="brandLogo" src="/brand/fantasy-mpl-emblem.png" alt="Fantasy MPL emblem"/><span><b>Fantasy MPL</b><small>FANTASY · PREDICTIONS · COMMUNITY</small></span></div>}

function Auth({onComplete}:{onComplete:(name:string,email:string)=>void}){
  const [name,setName]=useState('');const [email,setEmail]=useState('');const [error,setError]=useState('');
  function submit(e:FormEvent){e.preventDefault();if(name.trim().length<3){setError('Display name must contain at least 3 characters.');return}if(!email.includes('@')){setError('Enter a valid email address.');return}onComplete(name.trim(),email.trim())}
  return <div className="authPage brandLaunch"><div className="authGlow one"/><div className="authGlow two"/><div className="authIntro"><Logo/><div className="seasonTag"><i/> SEASON 18 · THREE REGIONS</div><h1>Build your roster.<br/><em>Back your region.</em></h1><p>The home of regional MPL fantasy. Predict fixtures, manage professional players and compete with your community.</p><div className="regionFlags"><span>🇲🇾</span><span>🇮🇩</span><span>🇵🇭</span><b>Three leagues. Three identities. One platform.</b></div></div><form className="authCard" onSubmit={submit}><span className="step">FIRST ACCESS</span><h2>Create your manager profile</h2><p>This working preview saves your account locally in this browser.</p><label>DISPLAY NAME<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. AqilZ" autoFocus/></label><label>EMAIL ADDRESS<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" type="email"/></label>{error&&<div className="formError">{error}</div>}<button className="primary" type="submit">Enter the arena <span>→</span></button><div className="demoNote"><i>✓</i><span>No password is required for this local preview. Production authentication will use Supabase.</span></div></form></div>
}

function RegionGate({joined,onChoose,close}:{joined:Region[];onChoose:(r:Region)=>void;close?:()=>void}){
  return <div className="regionGate"><div className="gateBox">{close&&<button className="close" onClick={close}>×</button>}<Logo/><span className="seasonTag"><i/> FANTASY MPL · SEASON 18</span><h1>Choose your battleground</h1><p>Every region is its own competition with separate predictions, rosters, leagues and rankings.</p><div className="regionCards">{(Object.keys(REGIONS) as Region[]).map(r=><button key={r} className={`regionCard region${r}`} onClick={()=>onChoose(r)}><span className="leagueLogo"><img src={REGIONS[r].logo} alt={`${REGIONS[r].name} logo`}/><i>{REGIONS[r].flag}</i></span><span className="regionText"><strong>{REGIONS[r].name}</strong><small>{r==='MY'?'Compete with Malaysia’s MPL community.':r==='ID'?'Challenge Indonesia’s passionate managers.':'Climb the dedicated Philippine rankings.'}</small><b>{joined.includes(r)?'CONTINUE':'JOIN COMPETITION'} →</b></span></button>)}</div><div className="separateNote"><span>◈</span><p><b>Scores never mix.</b> Joining another region creates a new independent record.</p></div></div></div>
}

function Sidebar({view,setView,region}:{view:View;setView:(v:View)=>void;region:Region}){
 const items:[View,string,string][]=[['dashboard','⌂','Dashboard'],['predictions','✓','Predictions'],['fantasy','♜','My Fantasy Team'],['leagues','▥','My Leagues'],['leaderboard','▥','Leaderboards'],['admin','⚙','Admin Console']];
 return <aside><Logo/><div className="navLabel">{REGIONS[region].name}</div><nav>{items.map(([id,icon,label])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}><i>{icon}</i>{label}</button>)}</nav><div className="sideSeason"><span>SEASON 18</span><b>Week 5 of 8</b><div><i/></div><small>Playoffs begin in 23 days</small></div></aside>
}

function Topbar({session,region,onRegion,onAdmin,onSignOut}:{session:Session;region:Region;onRegion:()=>void;onAdmin:()=>void;onSignOut:()=>void}){
 const [menu,setMenu]=useState(false);
 return <header><div className="mobileBrand"><Logo/></div><button className="regionSwitch" onClick={onRegion}><span>{REGIONS[region].flag}</span><b>{REGIONS[region].name}</b><i>⌄</i></button><div className="topActions"><button className="bell">♢<i/></button><button className="profile" onClick={()=>setMenu(!menu)}><span>{session.name.slice(0,2).toUpperCase()}</span><b>{session.name}</b><i>⌄</i></button>{menu&&<div className="profileMenu"><small>{session.email}</small><button className="adminMenuBtn" onClick={()=>{onAdmin();setMenu(false)}}>⚙ Admin console</button><button onClick={onSignOut}>Sign out</button></div>}</div></header>
}

function Dashboard({session,region,setView,picks,savePick}:{session:Session;region:Region;setView:(v:View)=>void;picks:Record<string,string>;savePick:(k:string,v:string)=>void}){
 const made=MATCHES[region].filter(m=>picks[m.id]).length;
 return <div className="page"><section className="hero"><div><span className="seasonTag"><i/> SEASON 18 · WEEK 5 LIVE</span><h1>Welcome back, {session.name}.<br/><em>Your region. Your legacy.</em></h1><p>You are competing exclusively in {REGIONS[region].name}. Make this week’s calls and manage your regional roster.</p><div className="heroActions"><button className="primary" onClick={()=>setView('predictions')}>Make this week’s picks</button><button className="secondary" onClick={()=>setView('fantasy')}>View my team</button></div></div><div className="heroLeague"><img src={REGIONS[region].logo} alt="League logo"/><span>{REGIONS[region].flag} REGIONAL HUB</span></div></section><div className="stats"><Stat label="REGIONAL POINTS" value="1,248" note="▲ 126 this week"/><Stat label="REGIONAL RANK" value="#284" note="▲ 37 places"/><Stat label="PREDICTION ACCURACY" value="72%" sub="18 of 25 correct"/><Stat label="WEEK 5 PICKS" value={`${made}/2`} note={made===2?'All set':'Complete your picks'}/></div><div className="dashboardGrid"><section className="panel"><div className="panelHead"><div><h2>Upcoming predictions</h2><p>{REGIONS[region].name} only</p></div><button className="textBtn" onClick={()=>setView('predictions')}>VIEW ALL</button></div>{MATCHES[region].map(m=><MiniMatch key={m.id} match={m} selected={picks[m.id]} select={v=>savePick(m.id,v)}/>)}</section><Standings region={region}/></div><p className="prototypeLabel">WORKING MVP · SAMPLE FIXTURES AND SCORES FOR PRODUCT TESTING</p></div>
}

function Stat({label,value,note,sub}:{label:string;value:string;note?:string;sub?:string}){return <div className="stat"><small>{label}</small><strong>{value}</strong>{note?<span>{note}</span>:<em>{sub}</em>}</div>}
function MiniMatch({match,selected,select}:{match:Match;selected?:string;select:(v:string)=>void}){return <div className="miniMatch"><div className="matchMeta"><span>{match.time} · WEEK 5</span><span>◷ Locks at match start</span></div><div className="teams"><Team code={match.homeCode} name={match.home}/><b>VS</b><Team code={match.awayCode} name={match.away} right/></div><div className="quickPicks"><button className={selected===match.homeCode?'selected':''} onClick={()=>select(match.homeCode)}>{match.homeCode}</button><button className={selected==='2-1'?'selected':''} onClick={()=>select('2-1')}>Exact 2–1</button><button className={selected===match.awayCode?'selected':''} onClick={()=>select(match.awayCode)}>{match.awayCode}</button></div></div>}
function Team({code,name,right}:{code:string;name:string;right?:boolean}){return <div className={`team ${right?'right':''}`}><span className={`teamBadge c${code.replace(/\s/g,'')}`}>{code.slice(0,4)}</span><strong>{name}</strong></div>}

function Standings({region}:{region:Region}){return <section className="panel standings"><div className="panelHead"><div><h2>Borneo Rivals</h2><p>{REGIONS[region].name} private league</p></div><button className="textBtn">VIEW</button></div>{[['1','Kuro','1,402','▲ 2'],['2','Minn','1,337','—'],['3','You','1,248','▲ 1'],['4','Fikri','1,195','▼ 2'],['5','Jelo','1,164','—']].map(x=><div className={`standing ${x[1]==='You'?'you':''}`} key={x[1]}><span>{x[0]}</span><i>{x[1].slice(0,2).toUpperCase()}</i><b>{x[1]}</b><small>{x[3]}</small><strong>{x[2]}</strong></div>)}</section>}

function Predictions({region,picks,scores,submittedAt,savePick,saveScore,submit,notify}:{region:Region;picks:Record<string,string>;scores:Record<string,string>;submittedAt?:string;savePick:(k:string,v:string)=>void;saveScore:(k:string,v:string)=>void;submit:()=>void;notify:(s:string)=>void}){
 const [tab,setTab]=useState<'picks'|'history'>('picks');const complete=MATCHES[region].every(m=>picks[m.id])&&Boolean(picks[`${region}-mvp`]);
 return <div className="page"><PageBanner tag={`${REGIONS[region].name.toUpperCase()} · WEEK 5`} title="Prediction Hub" copy="Pick every series winner, exact score and the regional weekly MVP." side={submittedAt?'SUBMITTED':'18:42:16'} sideLabel={submittedAt?'WEEK 5 STATUS':'PICKS LOCK IN'}/><div className="gameTabs"><button className={tab==='picks'?'active':''} onClick={()=>setTab('picks')}>Make picks</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}>History & points</button></div>{tab==='picks'?<><div className="submissionStatus"><div className={complete?'ready':'pending'}>{complete?'✓':'!'}</div><div><b>{complete?'Your prediction card is complete':'Complete all required selections'}</b><p>{complete?'Submit before the regional deadline. You may edit and resubmit until picks lock.':'Choose a winner for every series and one weekly MVP.'}</p></div><strong>{MATCHES[region].filter(m=>picks[m.id]).length+Number(Boolean(picks[`${region}-mvp`]))} / {MATCHES[region].length+1}</strong></div><div className="sectionTitle"><div><h2>Match picks</h2><p>+30 winner · +20 exact score · up to +15 upset bonus</p></div><span className="competitionPill">{REGIONS[region].flag} {REGIONS[region].name} ONLY</span></div><section className="panel">{MATCHES[region].map(m=><div className="fullMatch" key={m.id}><div className="matchMeta"><span>{m.time} · WEEK 5</span><span>◷ Locks at match start</span></div><div className="teams"><Team code={m.homeCode} name={m.home}/><b>VS</b><Team code={m.awayCode} name={m.away} right/></div><div className="predictionControls"><button className={picks[m.id]===m.homeCode?'selected':''} onClick={()=>savePick(m.id,m.homeCode)}>{m.homeCode} WIN</button><select value={scores[m.id]||''} onChange={e=>saveScore(m.id,e.target.value)}><option value="">Exact score (optional)</option><option>2–0</option><option>2–1</option><option>3–0</option><option>3–1</option><option>3–2</option></select><button className={picks[m.id]===m.awayCode?'selected':''} onClick={()=>savePick(m.id,m.awayCode)}>{m.awayCode} WIN</button></div></div>)}</section><div className="sectionTitle"><div><h2>Weekly MVP</h2><p>Choose one standout player · correct selection earns +100 points</p></div></div><section className="panel mvpPanel"><div className="mvpGrid">{MVP[region].map(p=>{const key=`${region}-mvp`;return <button className={`mvpCard ${picks[key]===p.name?'selected':''}`} key={p.name} onClick={()=>savePick(key,p.name)}><span className="playerFace">♟</span><strong>{p.name}</strong><small>{p.role} · {p.team}</small><b>{picks[key]===p.name?'✓ SELECTED':'MVP PICK'}</b></button>})}</div><div className="saveBar"><span>{submittedAt?`Last submitted ${new Date(submittedAt).toLocaleString()}`:'Selections are not official until submitted.'}</span><button className="primary" disabled={!complete} onClick={submit}>{submittedAt?'Update submission':'Submit Week 5 predictions'}</button></div></section></>:<PredictionHistory region={region}/>}</div>
}

function PredictionHistory({region}:{region:Region}){const rows=[{type:'Series winner',pick:region==='MY'?'SRG':'ONIC',result:'Correct',pts:30},{type:'Exact score',pick:'2–1',result:'Correct',pts:20},{type:'Series winner',pick:'Home team',result:'Incorrect',pts:0},{type:'Weekly MVP',pick:MVP[region][1].name,result:'Correct',pts:100},{type:'Perfect week bonus',pick:'—',result:'Not earned',pts:0}];return <div className="historyWrap"><div className="historySummary"><div><small>WEEK 4 POINTS</small><strong>150</strong><span>pts</span></div><div><small>CORRECT PICKS</small><strong>3 / 4</strong></div><div><small>SEASON ACCURACY</small><strong>72%</strong></div></div><section className="panel"><div className="panelHead"><div><h2>Week 4 points breakdown</h2><p>Finalized regional results</p></div><span className="finalized">✓ FINALIZED</span></div><div className="historyTable"><div className="historyHead"><span>TYPE</span><span>YOUR PICK</span><span>RESULT</span><span>POINTS</span></div>{rows.map((r,i)=><div className="historyRow" key={i}><span>{r.type}</span><b>{r.pick}</b><em className={r.pts?'correct':'miss'}>{r.result}</em><strong className={r.pts?'earned':''}>{r.pts?`+${r.pts}`:'0'}</strong></div>)}</div></section><div className="pointsExplain"><span>i</span><p><b>Every point is traceable.</b> Once admins finalize official results, your ledger shows the rule and source behind every award or correction.</p></div></div>}

function PageBanner({tag,title,copy,side,sideLabel}:{tag:string;title:string;copy:string;side:string;sideLabel:string}){return <section className="pageBanner"><div><span className="seasonTag"><i/> {tag}</span><h1>{title}</h1><p>{copy}</p></div><div className="bannerSide"><small>{sideLabel}</small><strong>{side}</strong></div></section>}

function Fantasy({region,captain:storedCaptain,rosterNames,transfers,saveCaptain,makeTransfer,notify}:{region:Region;captain?:string;rosterNames?:string[];transfers:number;saveCaptain:(s:string)=>void;makeTransfer:(outName:string,inName:string)=>void;notify:(s:string)=>void}){
 const [market,setMarket]=useState(false);const defaults=ROSTERS[region];const names=rosterNames||defaults.map(p=>p.name);const roster=names.map((name,i)=>{const original=defaults.find(p=>p.name===name);const pool=DRAFT_POOL[region].find(p=>p.name===name);return original||{name,role:pool?.role||defaults[i].role,pts:0}});const captain=storedCaptain&&names.includes(storedCaptain)?storedCaptain:roster[0].name;
 return <div className="page"><PageBanner tag="PRIVATE LEAGUE · 8 MAN" title="Borneo Rivals Squad" copy={`Season-long ${REGIONS[region].name} roster · every pro has one owner per league.`} side="286 PTS" sideLabel="WEEK 5 SCORE"/><div className="fantasyGrid"><section className="pitch">{roster.map((p,i)=><button key={p.name} className={`rosterSlot slot${i} ${captain===p.name?'captain':''}`} onClick={()=>saveCaptain(p.name)}><span>{region}</span><i>♟</i><strong>{p.name}</strong><small>{p.role} · {p.pts} pts</small>{captain===p.name&&<b>C</b>}</button>)}</section><section className="panel draftInfo"><div className="panelHead"><div><h2>League control</h2><p>Season-long snake draft</p></div><span className="complete">ACTIVE</span></div><Info label="CAPTAIN BOOST" value={`2× points · ${captain}`}/><Info label="TRANSFERS REMAINING" value={`${transfers} / 3 this split`}/><Info label="LINEUP LOCK" value="Saturday · 2:55 PM"/><h3>League activity</h3><div className="activity"><i/><p><b>You</b> made {captain} captain for Week 5.</p></div><div className="activity"><i/><p><b>Kuro</b> transferred in a new Gold Laner.</p></div><button className="primary wide" onClick={()=>setMarket(true)}>Manage roster</button></section></div>{market&&<TransferMarket region={region} roster={roster} transfers={transfers} close={()=>setMarket(false)} transfer={(a,b)=>{makeTransfer(a,b);setMarket(false)}} notify={notify}/>}<div className="ruleGrid"><Rule value="+3" title="Kill" copy="Points for every official match kill."/><Rule value="+1" title="Assist" copy="Rewards support and team participation."/><Rule value="2×" title="Captain" copy="Your chosen captain doubles weekly points."/></div></div>
}
function TransferMarket({region,roster,transfers,close,transfer,notify}:{region:Region;roster:{name:string;role:string;pts:number}[];transfers:number;close:()=>void;transfer:(a:string,b:string)=>void;notify:(s:string)=>void}){const [out,setOut]=useState('');const [incoming,setIncoming]=useState('');const selected=roster.find(p=>p.name===out);const available=DRAFT_POOL[region].filter(p=>!roster.some(r=>r.name===p.name)&&(!selected||p.role.toLowerCase()===selected.role.toLowerCase()));return <div className="modalShade"><div className="modalCard transferModal"><button className="close" onClick={close}>×</button><span className="seasonTag"><i/> {REGIONS[region].name.toUpperCase()} FREE AGENTS</span><h2>Manage your roster</h2><p>Transfer players role-for-role. Your regional allowance resets according to league rules.</p><div className="transferBalance"><span>⇄</span><div><small>TRANSFERS REMAINING</small><strong>{transfers} of 3</strong></div><div className="transferDots">{[1,2,3].map(n=><i className={n<=transfers?'left':''} key={n}/>)}</div></div><h3>1. Choose a player to release</h3><div className="releaseGrid">{roster.map(p=><button className={out===p.name?'selected':''} onClick={()=>{setOut(p.name);setIncoming('')}} key={p.name}><i>♟</i><span><b>{p.name}</b><small>{p.role} · {p.pts} pts</small></span><em>{out===p.name?'✓':'SELECT'}</em></button>)}</div>{out&&<><h3>2. Select an available {selected?.role}</h3><div className="freeAgentList">{available.length?available.map(p=><button className={incoming===p.name?'selected':''} onClick={()=>setIncoming(p.name)} key={p.name}><span className="agentRating">{p.rating}</span><i>♟</i><span><b>{p.name}</b><small>{p.team} · {p.role}</small></span><em>{incoming===p.name?'✓ SELECTED':'+ ADD'}</em></button>):<p>No same-role free agents are available in this demo pool.</p>}</div></>}<div className="transferFooter"><p>{incoming?`${out} → ${incoming}`:'Select both players to confirm the transfer.'}</p><button className="primary" disabled={!out||!incoming||transfers<1} onClick={()=>transfers>0?transfer(out,incoming):notify('No transfers remaining.')}>Confirm transfer</button></div></div></div>}

function Info({label,value}:{label:string;value:string}){return <div className="info"><small>{label}</small><strong>{value}</strong></div>}
function Rule({value,title,copy}:{value:string;title:string;copy:string}){return <div className="rule"><span>{value}</span><h3>{title}</h3><p>{copy}</p></div>}

type LocalLeague={id:string;name:string;region:Region;code:string;managers:number;status:'forming'|'drafting'|'active';members:string[];picks:{manager:string;player:string;role:string}[]};
const DRAFT_POOL:Record<Region,{name:string;role:string;team:string;rating:number}[]>={
 MY:[{name:'Sekys',role:'Jungle',team:'SRG',rating:94},{name:'Innocent',role:'Gold',team:'SRG',rating:92},{name:'Stormie',role:'Mid',team:'ONIC',rating:89},{name:'Xorn',role:'Roam',team:'HB',rating:87},{name:'Yums',role:'EXP',team:'TFL',rating:85},{name:'Chibi',role:'Jungle',team:'TFL',rating:84},{name:'CikuGais',role:'Gold',team:'VMS',rating:82},{name:'Pabz',role:'Roam',team:'ONIC',rating:80},{name:'Momo',role:'EXP',team:'HB',rating:79},{name:'Rival',role:'Mid',team:'VMS',rating:77}],
 ID:[{name:'Kairi',role:'Jungle',team:'ONIC',rating:95},{name:'Skylar',role:'Gold',team:'RRQ',rating:93},{name:'Sanz',role:'Mid',team:'ONIC',rating:91},{name:'Kiboy',role:'Roam',team:'ONIC',rating:89},{name:'Dyrennn',role:'EXP',team:'BTR',rating:87},{name:'Alberttt',role:'Jungle',team:'EVOS',rating:86},{name:'Kyy',role:'Roam',team:'BTR',rating:84},{name:'R7',role:'EXP',team:'RRQ',rating:82},{name:'Moreno',role:'Mid',team:'BTR',rating:81},{name:'Branz',role:'Gold',team:'EVOS',rating:79}],
 PH:[{name:'KarlTzy',role:'Jungle',team:'TLPH',rating:95},{name:'Kelra',role:'Gold',team:'RORA',rating:94},{name:'Sanford',role:'EXP',team:'TLPH',rating:92},{name:'Sanji',role:'Mid',team:'TLPH',rating:90},{name:'Oheb',role:'Gold',team:'FCAP',rating:88},{name:'Yawi',role:'Roam',team:'RORA',rating:86},{name:'Kirk',role:'EXP',team:'ONIC',rating:84},{name:'K1NGKONG',role:'Jungle',team:'ONIC',rating:83},{name:'Super Frince',role:'Mid',team:'FCAP',rating:81},{name:'Light',role:'Roam',team:'RSG',rating:80}]
};

function Leagues({region,notify}:{region:Region;notify:(s:string)=>void}){
 const [code,setCode]=useState('');const [leagues,setLeagues]=useState<LocalLeague[]>([]);const [creating,setCreating]=useState(false);const [open,setOpen]=useState<LocalLeague|null>(null);
 useEffect(()=>{try{setLeagues(JSON.parse(localStorage.getItem('fmpl_leagues')||'[]'))}catch{}},[]);
 function persist(next:LocalLeague[]){setLeagues(next);localStorage.setItem('fmpl_leagues',JSON.stringify(next))}
 function create(name:string,managers:number){const code=Math.random().toString(36).slice(2,8).toUpperCase();const l:LocalLeague={id:crypto.randomUUID(),name,region,code,managers,status:'forming',members:['You','Kuro','Minn','Fikri'].slice(0,Math.min(managers,4)),picks:[]};persist([...leagues,l]);setCreating(false);setOpen(l);notify(`League created — invite code ${code}`)}
 function updateLeague(l:LocalLeague){persist(leagues.map(x=>x.id===l.id?l:x));setOpen(l)}
 const regional=leagues.filter(l=>l.region===region);
 return <div className="page"><PageBanner tag={`${REGIONS[region].name.toUpperCase()} LEAGUES`} title="Play with your people" copy="Create a private league, invite friends and draft unique regional players." side={`${regional.length} / 5`} sideLabel="YOUR LEAGUES"/><div className="leagueActions"><section className="createCard"><span>＋</span><h2>Create a league</h2><p>Become commissioner, choose 4–10 managers and schedule a live snake draft.</p><button className="primary" onClick={()=>setCreating(true)}>Create private league</button></section><section className="joinCard"><span>⌁</span><h2>Join with a code</h2><p>Enter the six-character invite code shared by your commissioner.</p><div><input value={code} maxLength={6} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="ABC123"/><button className="primary" onClick={()=>{const found=leagues.find(l=>l.code===code&&l.region===region);found?(setOpen(found),notify('League found!')):notify('No regional league found for that code.')}}>Join</button></div></section></div><div className="sectionTitle"><div><h2>Your leagues</h2><p>Private competitions in {REGIONS[region].name}</p></div></div>{regional.length===0?<section className="emptyLeague"><span>◇</span><h3>Your league room is empty</h3><p>Create the first {REGIONS[region].name} league and invite your rivals.</p></section>:regional.map((l,i)=><section className="panel leagueRow" key={l.id}><span className="leagueIcon">{l.name.slice(0,2).toUpperCase()}</span><div><h3>{l.name}</h3><p>{l.managers} managers · {l.status==='forming'?'Waiting room':l.status==='drafting'?'Draft live':'Season active'}</p></div><div><small>YOUR RANK</small><strong>{l.status==='active'?'#3':'—'}</strong></div><div><small>PLAYERS</small><strong>{l.picks.filter(p=>p.manager==='You').length}</strong></div><button className="secondary" onClick={()=>setOpen(l)}>Open league</button></section>)}
 {creating&&<CreateLeagueModal region={region} close={()=>setCreating(false)} create={create}/>} {open&&<LeagueRoom league={open} close={()=>setOpen(null)} update={updateLeague} notify={notify}/>}</div>
}

function CreateLeagueModal({region,close,create}:{region:Region;close:()=>void;create:(n:string,m:number)=>void}){const [name,setName]=useState('');const [managers,setManagers]=useState(8);return <div className="modalShade"><div className="modalCard createModal"><button className="close" onClick={close}>×</button><span className="seasonTag"><i/> {REGIONS[region].name.toUpperCase()}</span><h2>Create your private league</h2><p>This league, its draft pool, roster and points will stay inside {REGIONS[region].name}.</p><label>LEAGUE NAME<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Borneo Rivals" autoFocus/></label><label>NUMBER OF MANAGERS<div className="managerChoices">{[4,6,8,10].map(n=><button key={n} className={managers===n?'selected':''} onClick={()=>setManagers(n)}>{n}</button>)}</div></label><div className="formatSummary"><span>⇄</span><div><b>Snake draft</b><small>60 seconds per pick · unique player ownership</small></div></div><button className="primary wide" disabled={name.trim().length<3} onClick={()=>create(name.trim(),managers)}>Create league & get invite code</button></div></div>}

function LeagueRoom({league,close,update,notify}:{league:LocalLeague;close:()=>void;update:(l:LocalLeague)=>void;notify:(s:string)=>void}){
 const [draft,setDraft]=useState(league.status==='drafting');
 if(draft)return <DraftRoom league={league} close={()=>{setDraft(false);close()}} update={update} notify={notify}/>;
 const missing=league.managers-league.members.length;
 function fill(){const bots=['Jelo','Marauder','VexanaMain','KielV','Ardiansyah','NexplayKid'];const next={...league,members:[...league.members,...bots.slice(0,missing)]};update(next);notify('Demo managers joined the waiting room.')}
 function begin(){if(missing>0){notify('Fill the league before starting the draft.');return}const next={...league,status:'drafting' as const};update(next);setDraft(true)}
 return <div className="modalShade"><div className="modalCard leagueRoom"><button className="close" onClick={close}>×</button><div className="roomTop"><span className="leagueIcon">{league.name.slice(0,2).toUpperCase()}</span><div><span className="seasonTag"><i/> {REGIONS[league.region].name}</span><h2>{league.name}</h2><p>Invite code <button className="copyCode" onClick={()=>{navigator.clipboard?.writeText(league.code);notify('Invite code copied!')}}>{league.code} ⧉</button></p></div></div><div className="roomStatus"><div><small>MANAGERS</small><strong>{league.members.length} / {league.managers}</strong></div><div><small>FORMAT</small><strong>Snake draft</strong></div><div><small>PICK TIMER</small><strong>60 sec</strong></div></div><h3>Draft lobby</h3><div className="memberGrid">{Array.from({length:league.managers},(_,i)=>league.members[i]||null).map((m,i)=><div className={`member ${m?'joined':''}`} key={i}><span>{m?m.slice(0,2).toUpperCase():'+'}</span><div><b>{m||'Open seat'}</b><small>{i===0?'Commissioner':m?'Ready':'Waiting for manager'}</small></div>{m&&<i>✓</i>}</div>)}</div>{missing>0?<button className="secondary wide" onClick={fill}>Fill {missing} open seats with demo managers</button>:<button className="primary wide" onClick={begin}>Start live snake draft →</button>}</div></div>
}

function DraftRoom({league,close,update,notify}:{league:LocalLeague;close:()=>void;update:(l:LocalLeague)=>void;notify:(s:string)=>void}){
 const [picks,setPicks]=useState(league.picks);const [current,setCurrent]=useState(league.picks.length);const [filter,setFilter]=useState('All');const total=Math.min(league.managers*2,DRAFT_POOL[league.region].length);const round=Math.floor(current/league.managers)+1;const pos=current%league.managers;const manager=round%2===1?league.members[pos]:league.members[league.managers-1-pos];const available=DRAFT_POOL[league.region].filter(p=>!picks.some(x=>x.player===p.name));
 useEffect(()=>{if(current>=total){const done={...league,status:'active' as const,picks};update(done);return}if(manager!=='You'){const timer=setTimeout(()=>{const choice=available[0];if(!choice)return;const next=[...picks,{manager,player:choice.name,role:choice.role}];setPicks(next);setCurrent(c=>c+1)},700);return()=>clearTimeout(timer)}},[current,manager]);
 function choose(p:{name:string;role:string}){if(manager!=='You'){notify(`Waiting for ${manager} to pick…`);return}const next=[...picks,{manager:'You',player:p.name,role:p.role}];setPicks(next);setCurrent(c=>c+1);notify(`${p.name} drafted to your roster!`)}
 const shown=available.filter(p=>filter==='All'||p.role===filter);
 return <div className="draftOverlay"><div className="draftHeader"><Logo/><div><small>{league.name} · ROUND {Math.min(round,2)}</small><strong>{current>=total?'DRAFT COMPLETE':manager==='You'?'YOU ARE ON THE CLOCK':`${manager} IS PICKING`}</strong></div><button onClick={close}>Exit draft</button></div><div className="draftOrder">{league.members.map((m,i)=><div className={m===manager&&current<total?'turn':''} key={m}><span>{i+1}</span><b>{m}</b><small>{picks.filter(p=>p.manager===m).length} picks</small></div>)}</div><div className="draftBody"><section><div className="draftTools"><div><h2>Available players</h2><p>{REGIONS[league.region].name} player pool · one owner per league</p></div><div>{['All','Jungle','Gold','Mid','EXP','Roam'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></div><div className="playerTable">{shown.map((p,i)=><button key={p.name} onClick={()=>choose(p)} disabled={manager!=='You'||current>=total}><span className="draftRank">{i+1}</span><i>♟</i><span><strong>{p.name}</strong><small>{p.team}</small></span><b>{p.role}</b><em>{p.rating}</em><u>{manager==='You'?'DRAFT':'LOCKED'}</u></button>)}</div></section><aside className="draftSide"><div className="clock"><small>CURRENT PICK</small><strong>#{Math.min(current+1,total)}</strong><span>{manager==='You'?'0:60':'AUTO PICK'}</span></div><h3>Your roster</h3>{picks.filter(p=>p.manager==='You').length===0?<p className="noPicks">Your drafted players will appear here.</p>:picks.filter(p=>p.manager==='You').map(p=><div className="myPick" key={p.player}><i>♟</i><span><b>{p.player}</b><small>{p.role}</small></span><strong>✓</strong></div>)}<h3>Recent picks</h3>{picks.slice(-4).reverse().map((p,i)=><div className="recentPick" key={p.player}><span>#{picks.length-i}</span><p><b>{p.player}</b><small>{p.manager}</small></p></div>)}</aside></div>{current>=total&&<div className="draftComplete"><span>✓</span><h2>Draft complete!</h2><p>Your first regional roster is ready for Week 5.</p><button className="primary" onClick={close}>View league</button></div>}</div>
}

type AdminTab='overview'|'matches'|'mvp'|'players';
function AdminConsole({region,notify}:{region:Region;notify:(s:string)=>void}){const [tab,setTab]=useState<AdminTab>('overview');const [results,setResults]=useState<Record<string,{home:string;away:string;state:string}>>({});const [mvp,setMvp]=useState('');const [job,setJob]=useState<'idle'|'running'|'done'>('idle');function score(){setJob('running');notify('Scoring job started…');setTimeout(()=>{setJob('done');notify('Scoring complete — 142 point transactions created.')},1700)}return <div className="page adminPage"><div className="adminBanner"><div><span className="adminBadge">⚙ ADMIN CONTROL CENTER</span><h1>{REGIONS[region].name}</h1><p>Manage Season 18 competition data for this region only.</p></div><div className="adminIdentity"><span>AZ</span><div><small>SIGNED IN AS</small><b>Platform administrator</b></div></div></div><div className="adminTabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>Overview</button><button className={tab==='matches'?'active':''} onClick={()=>setTab('matches')}>Matches & results</button><button className={tab==='mvp'?'active':''} onClick={()=>setTab('mvp')}>Weekly MVP</button><button className={tab==='players'?'active':''} onClick={()=>setTab('players')}>Players & teams</button></div>{tab==='overview'&&<AdminOverview region={region} job={job} score={score} setTab={setTab}/>} {tab==='matches'&&<AdminMatches region={region} results={results} setResults={setResults} notify={notify}/>} {tab==='mvp'&&<AdminMvp region={region} mvp={mvp} setMvp={setMvp} notify={notify}/>} {tab==='players'&&<AdminPlayers region={region} notify={notify}/>}</div>}
function AdminOverview({region,job,score,setTab}:{region:Region;job:string;score:()=>void;setTab:(t:AdminTab)=>void}){return <><div className="adminStats"><AdminStat label="REGISTERED MANAGERS" value="2,481" note="+186 this week"/><AdminStat label="WEEK 5 SUBMISSIONS" value="1,927" note="77.6% participation"/><AdminStat label="ACTIVE PRIVATE LEAGUES" value="364" note="2,742 drafted players"/><AdminStat label="PENDING RESULTS" value="2" note="Requires verification" warn/></div><div className="adminGrid"><section className="panel adminQueue"><div className="panelHead"><div><h2>Action queue</h2><p>Items requiring administrator attention</p></div></div><AdminAction color="red" title="2 match results pending" copy="Verify series scores and player statistics." action="Review" click={()=>setTab('matches')}/><AdminAction color="gold" title="Week 5 MVP not selected" copy={`Publish the official ${REGIONS[region].name} weekly MVP.`} action="Select" click={()=>setTab('mvp')}/><AdminAction color="cyan" title="Scoring ready to calculate" copy="All Week 4 results have passed validation." action={job==='running'?'Running…':job==='done'?'Completed':'Run scoring'} click={score}/></section><section className="panel scoreJob"><span className={job}>∑</span><h2>Scoring engine</h2><p>Calculates prediction and fantasy ledgers from finalized official results.</p><div><small>LAST SUCCESSFUL RUN</small><b>{job==='done'?'Just now':'Week 4 · Sunday 11:42 PM'}</b></div><button className="primary" disabled={job==='running'} onClick={score}>{job==='running'?'Calculating points…':'Calculate finalized results'}</button></section></div><section className="panel auditPanel"><div className="panelHead"><div><h2>Recent administrator activity</h2><p>Immutable regional audit trail</p></div><button className="textBtn">VIEW ALL</button></div>{[['Result finalized','SRG 2–1 HomeBois','AqilZ','12 min ago'],['Schedule updated','Week 5 · Match 2','AqilZ','1 hour ago'],['Player imported','10 roster records','System','Yesterday']].map(x=><div className="auditRow" key={x[1]}><span>✓</span><div><b>{x[0]}</b><small>{x[1]}</small></div><p>{x[2]}</p><time>{x[3]}</time></div>)}</section></>}
function AdminStat({label,value,note,warn}:{label:string;value:string;note:string;warn?:boolean}){return <div className="adminStat"><small>{label}</small><strong className={warn?'warn':''}>{value}</strong><span>{note}</span></div>}
function AdminAction({color,title,copy,action,click}:{color:string;title:string;copy:string;action:string;click:()=>void}){return <div className="adminAction"><i className={color}/><div><b>{title}</b><p>{copy}</p></div><button onClick={click}>{action} →</button></div>}
function AdminMatches({region,results,setResults,notify}:{region:Region;results:Record<string,{home:string;away:string;state:string}>;setResults:(x:Record<string,{home:string;away:string;state:string}>)=>void;notify:(s:string)=>void}){function update(id:string,key:'home'|'away',val:string){setResults({...results,[id]:{home:results[id]?.home||'',away:results[id]?.away||'',state:'draft',[key]:val}})}function finalize(m:Match){const r=results[m.id];if(!r?.home||!r?.away){notify('Enter both team scores before verification.');return}setResults({...results,[m.id]:{...r,state:'finalized'}});notify(`${m.homeCode} ${r.home}–${r.away} ${m.awayCode} finalized.`)}return <section className="panel adminMatches"><div className="panelHead"><div><h2>Week 5 match results</h2><p>{REGIONS[region].name} · server times shown in {REGIONS[region].timezone}</p></div><button className="secondary" onClick={()=>notify('CSV import preview opened — file upload comes with Supabase storage.')}>Import CSV</button></div>{MATCHES[region].map(m=>{const r=results[m.id];return <div className="resultRow" key={m.id}><div className="resultMeta"><span>{m.time}</span><b>{r?.state==='finalized'?'✓ FINALIZED':'AWAITING RESULT'}</b></div><div className="resultTeams"><span><Team code={m.homeCode} name={m.home}/><input type="number" min="0" max="4" value={r?.home||''} onChange={e=>update(m.id,'home',e.target.value)} disabled={r?.state==='finalized'}/></span><strong>—</strong><span><input type="number" min="0" max="4" value={r?.away||''} onChange={e=>update(m.id,'away',e.target.value)} disabled={r?.state==='finalized'}/><Team code={m.awayCode} name={m.away} right/></span></div><div className="resultActions"><button className="secondary" onClick={()=>notify('Player statistics editor opened in the next data step.')}>Player stats</button><button className="primary" disabled={r?.state==='finalized'} onClick={()=>finalize(m)}>{r?.state==='finalized'?'Finalized':'Verify & finalize'}</button></div></div>})}</section>}
function AdminMvp({region,mvp,setMvp,notify}:{region:Region;mvp:string;setMvp:(s:string)=>void;notify:(s:string)=>void}){const [published,setPublished]=useState(false);return <div className="adminFormGrid"><section className="panel mvpAdmin"><div className="panelHead"><div><h2>Official Week 5 MVP</h2><p>Selection awards +100 prediction points and +50 fantasy points</p></div><span className={published?'published':'draftState'}>{published?'✓ PUBLISHED':'DRAFT'}</span></div><label>SELECT OFFICIAL REGIONAL MVP<select value={mvp} onChange={e=>setMvp(e.target.value)} disabled={published}><option value="">Choose a player…</option>{MVP[region].map(p=><option key={p.name} value={p.name}>{p.name} · {p.role} · {p.team}</option>)}</select></label><label>SOURCE / ADMINISTRATOR NOTE<textarea placeholder="Official league announcement or verification note…" disabled={published}/></label><div className="publishWarning"><span>!</span><p>Publishing will create scoring transactions for all correct Week 5 MVP predictions. Corrections require an audited reversal.</p></div><button className="primary" disabled={!mvp||published} onClick={()=>{setPublished(true);notify(`${mvp} published as the official Week 5 MVP.`)}}>{published?'MVP published':'Publish official MVP'}</button></section><section className="panel mvpPreview"><small>PUBLIC PREVIEW</small><div className="playerFace">♟</div><span>{REGIONS[region].flag} WEEK 5 MVP</span><h2>{mvp||'Not selected'}</h2><p>{mvp?MVP[region].find(x=>x.name===mvp)?.team:'Choose a player to preview the announcement.'}</p></section></div>}
function AdminPlayers({region,notify}:{region:Region;notify:(s:string)=>void}){return <section className="panel"><div className="panelHead"><div><h2>Season 18 player registry</h2><p>{REGIONS[region].name} active fantasy pool</p></div><div className="adminHeadActions"><button className="secondary" onClick={()=>notify('CSV roster importer is prepared for database integration.')}>Import CSV</button><button className="primary" onClick={()=>notify('New player form opened in the next backend step.')}>+ Add player</button></div></div><div className="playerAdminHead"><span>PLAYER</span><span>TEAM</span><span>ROLE</span><span>RATING</span><span>STATUS</span><span></span></div>{DRAFT_POOL[region].map(p=><div className="playerAdminRow" key={p.name}><span><i>♟</i><b>{p.name}</b></span><span>{p.team}</span><span>{p.role}</span><strong>{p.rating}</strong><em>ACTIVE</em><button onClick={()=>notify(`${p.name} editor selected.`)}>Edit</button></div>)}</section>}

const BOARD_NAMES:Record<Region,string[]>={MY:['MarauderMY','KuroNeko','JohorDragons','MetaAiman','SabahSavage','PenangJungler','MelakaMage'],ID:['VexanaMain','Ardiansyah','RajaJungle','JakartaGold','KiboyFan','BandungMage','SurabayaEXP'],PH:['KielV','NexplayKid','ManilaMacro','CebuSavage','KelraFan','DavaoDraft','LuzonLegend']};
function Leaderboard({region,manager}:{region:Region;manager:string}){const [tab,setTab]=useState<'overall'|'prediction'|'fantasy'|'weekly'>('overall');const names=BOARD_NAMES[region];const base=names.map((name,i)=>({rank:i+1,name,country:REGIONS[region].flag,pred:980-i*49,fantasy:1006-i*41,accuracy:84-i,trend:i%3===0?'▲ '+(i+1):i%3===1?'—':'▼ 1'}));const you={rank:284,name:manager,country:REGIONS[region].flag,pred:612,fantasy:636,accuracy:72,trend:'▲ 37'};const score=(x:typeof you)=>tab==='prediction'?x.pred:tab==='fantasy'?x.fantasy:tab==='weekly'?Math.round((x.pred+x.fantasy)/6):x.pred+x.fantasy;return <div className="page"><PageBanner tag={`${REGIONS[region].name.toUpperCase()} RANKINGS`} title="Hall of Challengers" copy={`One regional table for ${REGIONS[region].name}. No cross-region scores.`} side="#284" sideLabel="YOUR REGIONAL RANK"/><div className="boardTabs"><button className={tab==='overall'?'active':''} onClick={()=>setTab('overall')}>Overall</button><button className={tab==='prediction'?'active':''} onClick={()=>setTab('prediction')}>Predictions</button><button className={tab==='fantasy'?'active':''} onClick={()=>setTab('fantasy')}>Fantasy</button><button className={tab==='weekly'?'active':''} onClick={()=>setTab('weekly')}>Week 5</button></div><div className="rankPodium">{[base[1],base[0],base[2]].map((u,i)=><div className={`podium p${i}`} key={u.name}><span>{i===1?'🥇':i===0?'🥈':'🥉'}</span><i>{u.name.slice(0,2).toUpperCase()}</i><strong>{u.name}</strong><small>{score(u).toLocaleString()} PTS</small><div>{i===1?'1':i===0?'2':'3'}</div></div>)}</div><section className="panel boardPanel"><div className="boardHead"><span>RANK</span><span>MANAGER</span><span>ACCURACY</span><span>PREDICTION</span><span>FANTASY</span><span>TREND</span><span>{tab.toUpperCase()}</span></div>{base.slice(3).map(u=><BoardRow key={u.name} u={u} points={score(u)}/>) }<div className="boardDivider"><span>•••</span><b>Your position</b><span>•••</span></div><BoardRow u={you} points={score(you)} you/></section><div className="rankNotice"><span>◈</span><p><b>Regional integrity:</b> this leaderboard only includes members and points from {REGIONS[region].name}. Switching region loads a completely separate ranking.</p></div></div>}
function BoardRow({u,points,you}:{u:{rank:number;name:string;country:string;pred:number;fantasy:number;accuracy:number;trend:string};points:number;you?:boolean}){return <div className={`boardRow ${you?'currentUser':''}`}><strong>#{u.rank}</strong><span className="boardUser"><i>{u.name.slice(0,2).toUpperCase()}</i><b>{u.name}</b>{you&&<em>YOU</em>}</span><span>{u.accuracy}%</span><span>{u.pred}</span><span>{u.fantasy}</span><span className={u.trend.startsWith('▲')?'up':u.trend.startsWith('▼')?'down':''}>{u.trend}</span><strong>{points.toLocaleString()}</strong></div>}

function MobileNav({view,setView}:{view:View;setView:(v:View)=>void}){return <nav className="mobileNav">{([['dashboard','⌂','HOME'],['predictions','✓','PICKS'],['fantasy','♜','TEAM'],['leagues','▥','LEAGUES'],['leaderboard','↗','RANK']] as [View,string,string][]).map(x=><button className={view===x[0]?'active':''} onClick={()=>setView(x[0])} key={x[0]}><i>{x[1]}</i>{x[2]}</button>)}</nav>}
