-- Fantasy MPL — cloud Meta Lab submissions and official scoring
-- Run after 027_official_regional_fantasy.sql
create table if not exists public.official_meta_results(
 week_id uuid primary key references public.competition_weeks(id) on delete cascade,most_picked_hero_id uuid not null references public.heroes(id),most_banned_hero_id uuid not null references public.heroes(id),most_contested_hero_id uuid not null references public.heroes(id),highest_ban_rate_range text not null,buffed_hero_id uuid not null references public.heroes(id),contest_increase_range text not null,flex_hero_id uuid not null references public.heroes(id),flex_role text not null,source_url text not null,finalized_at timestamptz not null default now(),finalized_by uuid references auth.users(id));
alter table public.official_meta_results enable row level security;create policy "public reads official meta results" on public.official_meta_results for select using(true);create policy "admins manage official meta results" on public.official_meta_results for all to authenticated using((select public.is_platform_admin())) with check((select public.is_platform_admin()));grant select on public.official_meta_results to anon,authenticated;
create or replace function public.normalize_meta_value(kind text,value text) returns text language sql immutable set search_path='' as $$select case kind when 'ban' then case value when 'UNDER 20%' then 'UNDER_20' when '20–39%' then '20_39' when '40–59%' then '40_59' when '60–79%' then '60_79' when '80% OR HIGHER' then '80_PLUS' else value end when 'increase' then case value when '+0–9%' then '0_9' when '+10–19%' then '10_19' when '+20–29%' then '20_29' when '+30% OR HIGHER' then '30_PLUS' else value end when 'role' then replace(value,' LANE','') else value end$$;
create or replace function public.save_my_meta_prediction(target_region text,payload jsonb,submit boolean default false)
returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=(select auth.uid());week_uuid uuid;locks timestamptz;h1 uuid;h2 uuid;h3 uuid;h4 uuid;h5 uuid;submitted timestamptz;
begin
 if uid is null then raise exception 'Authentication required';end if;week_uuid:=public.current_regional_fantasy_week(target_region);select meta_locks_at into locks from public.competition_weeks where id=week_uuid;if locks is null or now()>=locks then raise exception 'Meta Lab is locked for this week';end if;
 select id into h1 from public.heroes where upper(name::text)=upper(payload->>'mostPicked');select id into h2 from public.heroes where upper(name::text)=upper(payload->>'mostBanned');select id into h3 from public.heroes where upper(name::text)=upper(payload->>'mostContested');select id into h4 from public.heroes where upper(name::text)=upper(payload->>'buffHero');select id into h5 from public.heroes where upper(name::text)=upper(payload->>'flexHero');if nullif(payload->>'mostPicked','') is not null and h1 is null then raise exception 'Unknown hero';end if;submitted:=case when submit then now() else null end;
 insert into public.meta_predictions(user_id,week_id,most_picked_hero_id,most_banned_hero_id,most_contested_hero_id,highest_ban_rate_range,buffed_hero_id,expected_contest_increase,flex_hero_id,predicted_flex_role,submitted_at)
 values(uid,week_uuid,h1,h2,h3,public.normalize_meta_value('ban',payload->>'banRange'),h4,public.normalize_meta_value('increase',payload->>'buffRange'),h5,public.normalize_meta_value('role',payload->>'flexRole'),submitted)
 on conflict(user_id,week_id) do update set most_picked_hero_id=excluded.most_picked_hero_id,most_banned_hero_id=excluded.most_banned_hero_id,most_contested_hero_id=excluded.most_contested_hero_id,highest_ban_rate_range=excluded.highest_ban_rate_range,buffed_hero_id=excluded.buffed_hero_id,expected_contest_increase=excluded.expected_contest_increase,flex_hero_id=excluded.flex_hero_id,predicted_flex_role=excluded.predicted_flex_role,submitted_at=excluded.submitted_at,updated_at=now();return jsonb_build_object('saved',true,'submitted',submit,'week_id',week_uuid,'locks_at',locks);
end $$;
create or replace function public.admin_publish_meta_result(target_week uuid,payload jsonb,target_source_url text)
returns void language plpgsql security definer set search_path='' as $$
declare h1 uuid;h2 uuid;h3 uuid;h4 uuid;h5 uuid;
begin if not public.is_platform_admin() then raise exception 'Not authorized';end if;if target_source_url !~* '^https?://' then raise exception 'Valid source URL required';end if;select id into h1 from public.heroes where upper(name::text)=upper(payload->>'mostPicked');select id into h2 from public.heroes where upper(name::text)=upper(payload->>'mostBanned');select id into h3 from public.heroes where upper(name::text)=upper(payload->>'mostContested');select id into h4 from public.heroes where upper(name::text)=upper(payload->>'buffHero');select id into h5 from public.heroes where upper(name::text)=upper(payload->>'flexHero');if h1 is null or h2 is null or h3 is null or h4 is null or h5 is null then raise exception 'All official heroes are required';end if;
 insert into public.official_meta_results values(target_week,h1,h2,h3,public.normalize_meta_value('ban',payload->>'banRange'),h4,public.normalize_meta_value('increase',payload->>'buffRange'),h5,public.normalize_meta_value('role',payload->>'flexRole'),target_source_url,now(),(select auth.uid())) on conflict(week_id) do update set most_picked_hero_id=excluded.most_picked_hero_id,most_banned_hero_id=excluded.most_banned_hero_id,most_contested_hero_id=excluded.most_contested_hero_id,highest_ban_rate_range=excluded.highest_ban_rate_range,buffed_hero_id=excluded.buffed_hero_id,contest_increase_range=excluded.contest_increase_range,flex_hero_id=excluded.flex_hero_id,flex_role=excluded.flex_role,source_url=excluded.source_url,finalized_at=now(),finalized_by=(select auth.uid());end $$;
create or replace function public.score_week_meta(target_week uuid)
returns table(predictions_scored integer,transactions_created integer) language plpgsql security definer set search_path='' as $$
declare o public.official_meta_results;p record;pts numeric;breakdown text;counted integer:=0;created integer:=0;s public.seasons;
begin if not public.is_platform_admin() then raise exception 'Not authorized';end if;select * into o from public.official_meta_results where week_id=target_week;if not found then return query select 0,0;return;end if;select se.* into s from public.competition_weeks w join public.seasons se on se.id=w.season_id where w.id=target_week;
 for p in select * from public.meta_predictions where week_id=target_week and submitted_at is not null loop if exists(select 1 from public.score_transactions where source_table='meta_predictions' and source_id=p.id) then continue;end if;pts:=0;breakdown:='';if p.most_picked_hero_id=o.most_picked_hero_id then pts:=pts+40;breakdown:=breakdown||' most-picked';end if;if p.most_banned_hero_id=o.most_banned_hero_id then pts:=pts+40;breakdown:=breakdown||' most-banned';end if;if p.most_contested_hero_id=o.most_contested_hero_id then pts:=pts+50;breakdown:=breakdown||' most-contested';end if;if p.highest_ban_rate_range=o.highest_ban_rate_range then pts:=pts+20;end if;if p.buffed_hero_id=o.buffed_hero_id then pts:=pts+30;end if;if p.expected_contest_increase=o.contest_increase_range then pts:=pts+30;end if;if p.flex_hero_id=o.flex_hero_id and p.predicted_flex_role=o.flex_role then pts:=pts+100;end if;if pts=310 then pts:=pts+150;breakdown:=breakdown||' perfect-card';end if;if pts<>0 then insert into public.score_transactions(user_id,season_id,region_code,week_id,category,points,reason_code,description,source_table,source_id) values(p.user_id,s.id,s.region_code,target_week,'meta',pts,'meta_weekly','Weekly Meta Lab'||breakdown,'meta_predictions',p.id);created:=created+1;end if;counted:=counted+1;end loop;return query select counted,created;end $$;
grant execute on function public.save_my_meta_prediction(text,jsonb,boolean) to authenticated;grant execute on function public.admin_publish_meta_result(uuid,jsonb,text) to authenticated;grant execute on function public.score_week_meta(uuid) to authenticated;
select to_regprocedure('public.save_my_meta_prediction(text,jsonb,boolean)') is not null as live_meta_ready;
